# Generated by Django 2.1.2 on 2019-10-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('age', models.SmallIntegerField(default=0)),
                ('phone', models.SmallIntegerField(blank=True, db_index=True, default=0)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('info', models.TextField(max_length=500)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updata_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
