# Generated by Django 2.1.2 on 2019-10-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191021_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('create_time', models.IntegerField()),
                ('user', models.ManyToManyField(related_name='group', to='app.User')),
            ],
        ),
    ]
