# Generated by Django 2.1.2 on 2019-10-21 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_group'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='user',
            index_together={('username', 'phone')},
        ),
    ]
